language: python

python:
  - "3.7"
  - "3.6"
  - "3.8"

before_install:
  - pip install --upgrade pip
  - pip install poetry

script:
  - poetry run nox

branches:
  only:
    - master

notifications:
  email: false